In [1]:
import pandas as pd
import urllib.request

from bs4 import BeautifulSoup

In [2]:
# scrape players injiured stats by cummulative season 2018

source = urllib.request.urlopen('https://www.spotrac.com/nfl/injured-reserve/2018/').read()
soup = BeautifulSoup(source, "html.parser")
table = soup.find_all('table', attrs={'class':'datatable'})

In [3]:
c=0
for tb in table:
#     print(tb)
   c=c+1
print(c)

5

In [4]:
first_table=table[4]
table_rows = first_table.find_all('tr')

res = []
for tr in table_rows:
   td = tr.find_all('td')
   row = [tr.text.strip() for tr in td if tr.text.strip()]
   if row:
       res.append(row)
injNFLdf_18 = pd.DataFrame(res)

In [5]:
injNFLdf_18.head()

                0    1    2           3   4           5           6
0    Ryan Shazier  ILB  PIT        Back  17  $8,718,008  $8,718,008
1  Kam Chancellor   SS  SEA        Neck  17  $9,300,003  $6,800,000
2     Earl Thomas   FS  BAL         Leg  13  $7,952,945  $6,500,000
3      Aqib Talib   CB  LAR       Ankle   9  $5,823,531  $5,823,531
4      Jeff Allen    G   KC  Concussion  17  $7,375,008  $5,749,995

In [6]:
# Use the read_html function in Pandas to automatically scrape any tabular data from a page.
data_url = "https://www.foxsports.com/nfl/players"

#using the pandas .read_html() method, we can convert the html tables found the page to pandas dataframes.
# Note the result of the .read_html() method is a list of dataframes pulled from the page
url_tables = pd.read_html(data_url, encoding= "utf-8")

# Reference the first element of our list of dataframes
player_df = url_tables[0]
player_df

,Player,Team,No,Pos,Exp,Height,Weight,Age,School
0,"Abdullah, Ameer Abdullah, Ameer",MIN,31,RB,4,"5'9""",203,26,Nebraska
1,"Abernathy, Micah Abernathy, Micah",MIN,0,DB,0,"6'0""",195,22,-
2,"Aboushi, Oday Aboushi, Oday",DET,70,G,6,"6'5""",315,28,Virginia
3,"Abram, Johnathan Abram, Johnathan",OAK,0,DB,0,"6'0""",215,22,-
4,"Acho, Sam Acho, Sam",CHI,-,LB,8,"6'3""",259,30,Texas
5,"Adams, Andrew Adams, Andrew",DET,26,S,3,"5'11""",202,26,Connecticut
6,"Adams, Davante Adams, Davante",GB,17,WR,5,"6'1""",215,26,Fresno State
7,"Adams, Jamal Adams, Jamal",NYJ,33,S,2,"6'1""",213,23,LSU
8,"Adams, Jerell Adams, Jerell",HOU,89,TE,3,"6'5""",247,26,South Carolina
9,"Adams, Josh Adams, Josh",PHI,33,RB,1,"6'2""",217,22,Notre Dame
10,"Adams, Keion Adams, Keion",NYG,99,LB,2,"6'2""",245,24,Western Michigan
11,"Adams, Matthew Adams, Matthew",IND,49,LB,1,"6'1""",237,23,Houston
12,"Adams, Montravius Adams, Montravius",GB,90,NT,2,"6'4""",304,23,Auburn
13,"Adams, Paul Adams, Paul",NYG,0,T,0,"6'6""",315,24,-
14,"Adams, Tony Adams, Tony",MIA,61,G,1,"6'2""",315,-,North Carolina State
15,"Adams, Tyrell Adams, Tyrell",HOU,50,LB,4,"6'2""",228,27,West Georgia
16,"Addae, Jahleel Addae, Jahleel",HOU,37,S,6,"5'10""",195,29,Central Michigan
17,"Adderley, Nasir Adderley, Nasir",LAC,0,DB,0,"6'0""",200,22,-
18,"Addison, Mario Addison, Mario",CAR,97,DE,8,"6'3""",260,31,Troy
19,"Adeboyejo, Quincy Adeboyejo, Quincy",BAL,16,WR,2,"6'3""",197,24,Ole Miss
20,"Adeniyi, Olasunkanmi Adeniyi, Olasunkanmi",PIT,-,LB,1,"6'2""",255,21,Toledo
21,"Adeoye, Aaron Adeoye, Aaron",BAL,0,DE,0,"6'7""",237,25,-
22,"Adewusi, Tenny Adewusi, Tenny",NYG,0,DB,0,"6'1""",200,22,-
23,"Afriyie, Pat Afriyie, Pat",LAC,96,DE,1,"6'2""",240,22,Colgate
24,"Agasiva, Jordan Agasiva, Jordan",JAC,0,G,0,"6'3""",320,-,-

In [7]:
player_df["Player"]= player_df['Player'].str.split(', ').str[1]
player_df

,Player,Team,No,Pos,Exp,Height,Weight,Age,School
0,Ameer Abdullah,MIN,31,RB,4,"5'9""",203,26,Nebraska
1,Micah Abernathy,MIN,0,DB,0,"6'0""",195,22,-
2,Oday Aboushi,DET,70,G,6,"6'5""",315,28,Virginia
3,Johnathan Abram,OAK,0,DB,0,"6'0""",215,22,-
4,Sam Acho,CHI,-,LB,8,"6'3""",259,30,Texas
5,Andrew Adams,DET,26,S,3,"5'11""",202,26,Connecticut
6,Davante Adams,GB,17,WR,5,"6'1""",215,26,Fresno State
7,Jamal Adams,NYJ,33,S,2,"6'1""",213,23,LSU
8,Jerell Adams,HOU,89,TE,3,"6'5""",247,26,South Carolina
9,Josh Adams,PHI,33,RB,1,"6'2""",217,22,Notre Dame
10,Keion Adams,NYG,99,LB,2,"6'2""",245,24,Western Michigan
11,Matthew Adams,IND,49,LB,1,"6'1""",237,23,Houston
12,Montravius Adams,GB,90,NT,2,"6'4""",304,23,Auburn
13,Paul Adams,NYG,0,T,0,"6'6""",315,24,-
14,Tony Adams,MIA,61,G,1,"6'2""",315,-,North Carolina State
15,Tyrell Adams,HOU,50,LB,4,"6'2""",228,27,West Georgia
16,Jahleel Addae,HOU,37,S,6,"5'10""",195,29,Central Michigan
17,Nasir Adderley,LAC,0,DB,0,"6'0""",200,22,-
18,Mario Addison,CAR,97,DE,8,"6'3""",260,31,Troy
19,Quincy Adeboyejo,BAL,16,WR,2,"6'3""",197,24,Ole Miss
20,Olasunkanmi Adeniyi,PIT,-,LB,1,"6'2""",255,21,Toledo
21,Aaron Adeoye,BAL,0,DE,0,"6'7""",237,25,-
22,Tenny Adewusi,NYG,0,DB,0,"6'1""",200,22,-
23,Pat Afriyie,LAC,96,DE,1,"6'2""",240,22,Colgate
24,Jordan Agasiva,JAC,0,G,0,"6'3""",320,-,-

In [8]:
player_df.to_csv()

',Player,Team,No,Pos,Exp,Height,Weight,Age,School\n0,Ameer  Abdullah,MIN,31,RB,4,"5\'9""",203,26,Nebraska\n1,Micah  Abernathy,MIN,0,DB,0,"6\'0""",195,22,-\n2,Oday  Aboushi,DET,70,G,6,"6\'5""",315,28,Virginia\n3,Johnathan  Abram,OAK,0,DB,0,"6\'0""",215,22,-\n4,Sam  Acho,CHI,-,LB,8,"6\'3""",259,30,Texas\n5,Andrew  Adams,DET,26,S,3,"5\'11""",202,26,Connecticut\n6,Davante  Adams,GB,17,WR,5,"6\'1""",215,26,Fresno State\n7,Jamal  Adams,NYJ,33,S,2,"6\'1""",213,23,LSU\n8,Jerell  Adams,HOU,89,TE,3,"6\'5""",247,26,South Carolina\n9,Josh  Adams,PHI,33,RB,1,"6\'2""",217,22,Notre Dame\n10,Keion  Adams,NYG,99,LB,2,"6\'2""",245,24,Western Michigan\n11,Matthew  Adams,IND,49,LB,1,"6\'1""",237,23,Houston\n12,Montravius  Adams,GB,90,NT,2,"6\'4""",304,23,Auburn\n13,Paul  Adams,NYG,0,T,0,"6\'6""",315,24,-\n14,Tony  Adams,MIA,61,G,1,"6\'2""",315,-,North Carolina State\n15,Tyrell  Adams,HOU,50,LB,4,"6\'2""",228,27,West Georgia\n16,Jahleel  Addae,HOU,37,S,6,"5\'10""",195,29,Central Michigan\n17,Nasir  Adderley,LAC,0,DB,0,"6\'0""",200,22,-\n18,Mario  Addison,CAR,97,DE,8,"6\'3""",260,31,Troy\n19,Quincy  Adeboyejo,BAL,16,WR,2,"6\'3""",197,24,Ole Miss\n20,Olasunkanmi  Adeniyi,PIT,-,LB,1,"6\'2""",255,21,Toledo\n21,Aaron  Adeoye,BAL,0,DE,0,"6\'7""",237,25,-\n22,Tenny  Adewusi,NYG,0,DB,0,"6\'1""",200,22,-\n23,Pat  Afriyie,LAC,96,DE,1,"6\'2""",240,22,Colgate\n24,Jordan  Agasiva,JAC,0,G,0,"6\'3""",320,-,-\n'