In [150]:
import pandas as pd
import urllib.request

from bs4 import BeautifulSoup

In [151]:
# scrape players injured by cummulative season 2018

source = urllib.request.urlopen('https://www.spotrac.com/nhl/injured-reserve/2018/').read()
soup = BeautifulSoup(source, "html.parser")
table = soup.find_all('table', attrs={'class':'datatable'})

In [152]:
c=0
for tb in table:
#     print(tb)
    c=c+1
print(c)

5

In [153]:
first_table=table[4]
table_rows = first_table.find_all('tr')

res = []
for tr in table_rows:
    td = tr.find_all('td')
    row = [tr.text.strip() for tr in td if tr.text.strip()]
    if row:
        res.append(row)
injNHLdf_18 = pd.DataFrame(res)
# print(df.count)

#print(df)

In [154]:
injNHLdf_18 = pd.DataFrame(res, columns=["PLAYER", "POS", "TEAM", "REASONS", "WEEKS", "2018 CAP", "2018 CASH"])

injNHLdf_18.head()

              PLAYER POS TEAM          REASONS WEEKS     2018 CAP    2018 CASH
0     Filip Forsberg   C  NSH             Hand    38  $17,339,818  $17,339,818
1        Jack Eichel   C  BUF       Upper Body   167   $8,978,421   $8,978,421
2      Martin Hanzal   C  DAL  Upper Body/Back   242   $6,180,196   $6,505,444
3  Henrik Zetterberg  LW  DET             Back   186   $6,083,316   $6,083,316
4        Marc Methot   D  DAL       Lower Body   219   $5,769,336   $5,769,336

In [155]:
# scrape players injured by cummulative season 2017
source = urllib.request.urlopen('https://www.spotrac.com/nhl/injured-reserve/2017/').read()
soup = BeautifulSoup(source, "html.parser")
table = soup.find_all('table', attrs={'class':'datatable'})
first_table=table[4]
table_rows = first_table.find_all('tr')

res = []
for tr in table_rows:
    td = tr.find_all('td')
    row = [tr.text.strip() for tr in td if tr.text.strip()]
    if row:
        res.append(row)
injNHLdf_17 = pd.DataFrame(res)
# print(df.count)
injNHLdf_17 = pd.DataFrame(res, columns=["PLAYER", "POS", "TEAM", "REASONS", "WEEKS", "2017 CAP", "2017 CASH"])

injNHLdf_17.head()

,PLAYER,POS,TEAM,REASONS,WEEKS,2017 CAP,2017 CASH
0,Zach Bogosian,D,BUF,Leg/Lower Body/Ribs,"1,434","$40,449,528","$42,053,576"
1,Kris Letang,D,PIT,Lower Body/Upper Body,873,"$35,154,894","$35,154,894"
2,Ryan Callahan,RW,TBL,Upper Body/Lower Body,912,"$29,370,879","$32,915,757"
3,Semyon Varlamov,G,COL,Lower Body/Groin,906,"$29,675,708","$30,151,318"
4,Mikhail Grabovski,C,VGK,Concussion,627,"$16,855,014","$20,225,766"