In [162]:
import pandas as pd

In [163]:
file1 = "injNHLdata17.csv"
file2 = "injNHLdata18.csv"
file3 = "NHLBodstat_17.csv"
file4 = "NHLBodstat_18.csv"
file5 = "NHLTimeonIce_17.csv"
file6 = "NHLTimeonIce_18.csv"
file7 = "injCount17.csv"
file8 = "injCount18.csv"

injNHL_17data = pd.read_csv(file1)
injNHL_18data = pd.read_csv(file2)
injCntNHL_17 = pd.read_csv(file7)
injCntNHL_18 = pd.read_csv(file8)
NHLBodstat_17data = pd.read_csv(file3)
NHLBodstat_18data = pd.read_csv(file4)
NHLTimeonIce_17data = pd.read_csv(file5)
NHLTimeonIce_18data = pd.read_csv(file6)

In [164]:
injNHL_17data.head()

,Unnamed: 0,CAP HIT,CHIP,GAMES MISSED,INJURY TYPE,PLAYER,POSITION,SEASON,TEAM,GAMES MISSED.1
0,7060,0.68,33.170732,4,Upper body,"Blandisi, Joseph",F,2017/18,Anaheim,4
1,7061,0.90,164.634146,15,Lower body,"Boll, Jared",F,2017/18,Anaheim,15
2,7062,3.15,2957.926829,77,Illness,"Eaves, Patrick",F,2017/18,Anaheim,77
3,7063,3.15,115.243902,3,Lower body,"Eaves, Patrick",F,2017/18,Anaheim,3
4,7064,8.25,1911.585366,19,Facial,"Getzlaf, Ryan",F,2017/18,Anaheim,19

In [165]:
injNHL_17data = injNHL_17data.drop(['Unnamed: 0', 'GAMES MISSED.1', 'CAP HIT', 'CHIP'], axis=1)

In [166]:
injNHL_17data.head()

   GAMES MISSED INJURY TYPE            PLAYER POSITION   SEASON     TEAM
0             4  Upper body  Blandisi, Joseph        F  2017/18  Anaheim
1            15  Lower body       Boll, Jared        F  2017/18  Anaheim
2            77     Illness    Eaves, Patrick        F  2017/18  Anaheim
3             3  Lower body    Eaves, Patrick        F  2017/18  Anaheim
4            19      Facial     Getzlaf, Ryan        F  2017/18  Anaheim

In [167]:
NHLBodstat_17data.head()

   Unnamed: 0           PLAYER TEAM POSITION HEIGHT  WEIGHT   BIRTHDAY  AGE
0           0              Aal  TOR        C   6'0"     176  6/07/1993   26
1           1             Abbo  ANA       LW   5'9"     170  4/30/1988   31
2           2  Abdelkader, Jus  DET       LW   6'2"     214  2/25/1987   32
3           3       Aberg, Pon  EDM       LW  5'11"     196  9/23/1993   25
4           4      Abramov, Vi  CBJ       RW   5'9"     171  5/08/1998   21

In [168]:
NHLBodstat_17data = NHLBodstat_17data.drop(['Unnamed: 0'], axis=1)

In [197]:
NHLBodstat_17data.head(20)

,PLAYER,TEAM,POSITION,HEIGHT,WEIGHT,BIRTHDAY,AGE
0,Aal,TOR,C,"6'0""",176,6/07/1993,26
1,Abbo,ANA,LW,"5'9""",170,4/30/1988,31
2,"Abdelkader, Jus",DET,LW,"6'2""",214,2/25/1987,32
3,"Aberg, Pon",EDM,LW,"5'11""",196,9/23/1993,25
4,"Abramov, Vi",CBJ,RW,"5'9""",171,5/08/1998,21
5,"Acciari, Noel\nAcciari, Noel",BOS,C,"5'10""",208,12/01/1991,27
6,Acola,FLA,D,"6'0""",210,11/28/1990,28
7,"Addison, Jeremiah\nAddison, Jeremiah",MTL,LW,"6'0""",188,10/21/1996,22
8,Agos,BOS,LW,"6'0""",202,4/30/1992,27
9,"Agozzino, Andrew\nAgozzino, Andrew",COL,LW,"5'10""",187,1/03/1991,28
10,"Aho, Sebas",CAR,LW,"5'11""",172,7/26/1997,21
11,"Aho, Sebas",NYI,D,"5'10""",170,2/17/1996,23
12,"Alain, Alexandre\nAlain, Alexandre",MTL,C,"6'1""",173,3/03/1997,22
13,Alber,NYR,C,"5'11""",179,1/19/1989,30
14,"Allard, Frederic\nAllard, Frederic",NSH,D,"6'1""",179,12/27/1997,21
15,"Allen, Jake\nAllen, Jake",STL,G,"6'2""",203,8/07/1990,28
16,"Allen, Sco",ARZ,LW,"6'3""",198,7/06/1990,28
17,Al,COL,D,"6'4""",201,10/18/1991,27
18,"Alzner, Karl\nAlzner, Karl",MTL,D,"6'3""",217,9/24/1988,30
19,"Amadio, Michael\nAmadio, Michael",LA,C,"6'1""",204,5/13/1996,23

In [171]:
NHLTimeonIce_17data.head()

,Unnamed: 0,RK,PLAYER,TEAM,GP,G,A,PTS,+/-,TOI/G,SHFT,SHFT/G,PROD,POS
0,1,1,Dustin Byfuglien,WPG,80,13,39,52,10,27:27,2327,29.1,42:13,D
1,2,2,Drew Doughty,LA,82,12,32,44,8,27:09,2657,32.4,50:35,D
2,3,3,Ryan Suter,MIN,82,9,31,40,34,26:55,2319,28.3,55:11,D
3,4,4,Erik Karlsson,OTT,77,17,54,71,10,26:50,2425,31.5,29:06,D
4,5,5,Rasmus Ristolainen,BUF,79,6,39,45,-9,26:28,2341,29.6,46:28,D

In [172]:
NHLTimeonIce_17data = NHLTimeonIce_17data.drop(['Unnamed: 0', 'RK'], axis=1)

In [173]:
NHLTimeonIce_17data.head()

               PLAYER TEAM  GP   G   A PTS +/-  TOI/G  SHFT SHFT/G   PROD POS
0    Dustin Byfuglien  WPG  80  13  39  52  10  27:27  2327   29.1  42:13   D
1        Drew Doughty   LA  82  12  32  44   8  27:09  2657   32.4  50:35   D
2          Ryan Suter  MIN  82   9  31  40  34  26:55  2319   28.3  55:11   D
3       Erik Karlsson  OTT  77  17  54  71  10  26:50  2425   31.5  29:06   D
4  Rasmus Ristolainen  BUF  79   6  39  45  -9  26:28  2341   29.6  46:28   D

In [174]:
print (NHLTimeonIce_17data['PLAYER'].dtypes)
print (NHLBodstat_17data['PLAYER'].dtypes)
print (NHLBodstat_17data['PLAYER'].dtypes)

object
object
object

In [186]:
print(NHLTimeonIce_17data.columns)
print(NHLBodstat_17data.shape)

Index(['PLAYER', 'TEAM', 'GP', 'G', 'A', 'PTS', '+/-', 'TOI/G', 'SHFT',
       'SHFT/G', 'PROD', 'POS'],
      dtype='object')
(25, 7)

In [187]:
print(NHLBodstat_17data.columns)
print(NHLBodstat_17data.shape)

Index(['PLAYER', 'TEAM', 'POSITION', 'HEIGHT', 'WEIGHT', 'BIRTHDAY', 'AGE'], dtype='object')
(25, 7)

In [196]:
NHLTimeonIce_17data['PLAYER']=NHLTimeonIce_17data['PLAYER'].astype(str)
NHLBodstat_17data['PLAYER']=NHLBodstat_17data['PLAYER'].astype(str)

pd.merge(NHLTimeonIce_17data, NHLBodstat_17data, left_on ='PLAYER',right_on='PLAYER',how="left",sort=True)

,PLAYER,TEAM_x,GP,G,A,PTS,+/-,TOI/G,SHFT,SHFT/G,PROD,POS,TEAM_y,POSITION,HEIGHT,WEIGHT,BIRTHDAY,AGE
0,Alex Goligoski,ARI,82,6,30,36,-9,23:20,2356,28.7,53:08,D,NaN,NaN,NaN,NaN,NaN,NaN
1,Alex Pietrangelo,STL,80,14,34,48,3,25:17,2468,30.9,42:08,D,NaN,NaN,NaN,NaN,NaN,NaN
2,Alexander Edler,VAN,68,6,15,21,-20,24:19,1931,28.4,78:43,D,NaN,NaN,NaN,NaN,NaN,NaN
3,Anton Stralman,TB,73,5,17,22,1,22:54,1963,26.9,75:59,D,NaN,NaN,NaN,NaN,NaN,NaN
4,Brent Burns,SJ,82,29,47,76,19,24:52,2295,28.0,26:49,D,NaN,NaN,NaN,NaN,NaN,NaN
5,Cam Fowler,ANA,80,11,28,39,7,24:51,2258,28.2,50:58,D,NaN,NaN,NaN,NaN,NaN,NaN
6,Cody Ceci,OTT,79,2,15,17,-11,23:12,2418,30.6,107:50,D,NaN,NaN,NaN,NaN,NaN,NaN
7,Dion Phaneuf,OTT,81,9,21,30,-6,23:02,2476,30.6,62:12,D,NaN,NaN,NaN,NaN,NaN,NaN
8,Drew Doughty,LA,82,12,32,44,8,27:09,2657,32.4,50:35,D,NaN,NaN,NaN,NaN,NaN,NaN
9,Duncan Keith,CHI,80,6,47,53,22,25:37,2379,29.7,38:40,D,NaN,NaN,NaN,NaN,NaN,NaN
10,Dustin Byfuglien,WPG,80,13,39,52,10,27:27,2327,29.1,42:13,D,NaN,NaN,NaN,NaN,NaN,NaN
11,Erik Karlsson,OTT,77,17,54,71,10,26:50,2425,31.5,29:06,D,NaN,NaN,NaN,NaN,NaN,NaN
12,Hampus Lindholm,ANA,66,6,14,20,13,22:27,1786,27.1,74:05,D,NaN,NaN,NaN,NaN,NaN,NaN
13,Jaccob Slavin,CAR,82,5,29,34,23,23:26,2135,26.0,56:31,D,NaN,NaN,NaN,NaN,NaN,NaN
14,Jacob Trouba,WPG,60,8,25,33,4,24:58,1716,28.6,45:23,D,NaN,NaN,NaN,NaN,NaN,NaN
15,Jake Muzzin,LA,82,9,19,28,-21,22:18,2472,30.1,65:17,D,NaN,NaN,NaN,NaN,NaN,NaN
16,Jared Spurgeon,MIN,76,10,28,38,33,24:02,2084,27.4,48:04,D,NaN,NaN,NaN,NaN,NaN,NaN
17,Jay Bouwmeester,STL,81,1,14,15,6,22:24,2366,29.2,120:59,D,NaN,NaN,NaN,NaN,NaN,NaN
18,John Carlson,WSH,72,9,28,37,7,22:43,1916,26.6,44:11,D,NaN,NaN,NaN,NaN,NaN,NaN
19,John Klingberg,DAL,80,13,36,49,2,23:21,2209,27.6,38:07,D,NaN,NaN,NaN,NaN,NaN,NaN
20,Justin Faulk,CAR,75,17,20,37,-18,23:08,1987,26.5,46:54,D,NaN,NaN,NaN,NaN,NaN,NaN
21,Kris Letang,PIT,41,5,29,34,2,25:31,1207,29.4,30:46,D,NaN,NaN,NaN,NaN,NaN,NaN
22,Mark Giordano,CGY,81,12,27,39,22,23:35,2364,29.2,48:58,D,NaN,NaN,NaN,NaN,NaN,NaN
23,Mattias Ekholm,NSH,82,3,20,23,4,23:28,2330,28.4,83:38,D,NaN,NaN,NaN,NaN,NaN,NaN
24,Mike Green,DET,72,14,22,36,-20,23:33,2042,28.4,47:06,D,NaN,NaN,NaN,NaN,NaN,NaN
25,Nick Leddy,NYI,81,11,35,46,-3,22:43,1912,23.6,40:00,D,NaN,NaN,NaN,NaN,NaN,NaN
26,Oliver Ekman-Larsson,ARI,79,12,27,39,-25,24:37,2332,29.5,49:51,D,NaN,NaN,NaN,NaN,NaN,NaN
27,Oscar Klefbom,EDM,82,12,26,38,7,22:22,2197,26.8,48:16,D,NaN,NaN,NaN,NaN,NaN,NaN
28,P.K. Subban,NSH,66,10,30,40,-8,24:24,1860,28.2,40:16,D,NaN,NaN,NaN,NaN,NaN,NaN
29,PLAYER,TEAM,GP,G,A,PTS,+/-,TOI/G,SHFT,SHFT/G,PROD,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,PLAYER,TEAM,GP,G,A,PTS,+/-,TOI/G,SHFT,SHFT/G,PROD,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,PLAYER,TEAM,GP,G,A,PTS,+/-,TOI/G,SHFT,SHFT/G,PROD,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,Rasmus Ristolainen,BUF,79,6,39,45,-9,26:28,2341,29.6,46:28,D,NaN,NaN,NaN,NaN,NaN,NaN
33,Roman Josi,NSH,72,12,37,49,7,25:04,2076,28.8,36:50,D,NaN,NaN,NaN,NaN,NaN,NaN
34,Ryan Ellis,NSH,71,16,22,38,17,23:57,2028,28.6,44:45,D,NaN,NaN,NaN,NaN,NaN,NaN
35,Ryan McDonagh,NYR,77,6,36,42,20,24:21,2275,29.5,44:39,D,NaN,NaN,NaN,NaN,NaN,NaN
36,Ryan Suter,MIN,82,9,31,40,34,26:55,2319,28.3,55:11,D,NaN,NaN,NaN,NaN,NaN,NaN
37,Seth Jones,CBJ,75,12,30,42,6,23:24,2247,30.0,41:47,D,NaN,NaN,NaN,NaN,NaN,NaN
38,Shea Weber,MTL,78,17,25,42,20,25:04,2218,28.4,46:32,D,NaN,NaN,NaN,NaN,NaN,NaN
39,T.J. Brodie,CGY,82,6,30,36,-16,23:35,2379,29.0,53:42,D,NaN,NaN,NaN,NaN,NaN,NaN
40,Tyson Barrie,COL,74,7,31,38,-34,23:18,2050,27.7,45:23,D,NaN,NaN,NaN,NaN,NaN,NaN
41,Victor Hedman,TB,79,16,56,72,3,24:31,2201,27.9,26:53,D,NaN,NaN,NaN,NaN,NaN,NaN
42,Zdeno Chara,BOS,75,10,19,29,18,23:20,1958,26.1,60:20,D,NaN,NaN,NaN,NaN,NaN,NaN

In [191]:
NHL17_merg1

Empty DataFrame
Columns: [PLAYER, TEAM_x, GP, G, A, PTS, +/-, TOI/G, SHFT, SHFT/G, PROD, POS, TEAM_y, POSITION, HEIGHT, WEIGHT, BIRTHDAY, AGE]
Index: []